except Exception as e:
        print(i, e)